version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/server/QA-sprint-mission
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: '**'
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: scripts/after-deploy.sh
      timeout: 2000
      runas: root
