# 게시글 목록 조회
GET http://localhost:3000/articles?&offset=1&limit=10&&orderBy=like

###
# 게시글 상세 조회

GET http://localhost:3000/articles/2c027764-d7ef-4a94-8399-f15ffbf8f4da

###
# 게시글 등록
POST http://localhost:3000/articles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxNzMwNDc2OCwiZXhwIjoxNzE3MzA1NjY4fQ.0Neh8i3gQWCU0o0y01-Co8jsW8kiXKl3dW7H6wK94pY
Content-Type: application/json

{
  "title": "제가 아끼는 티모 인형입니다",
  "content": "버섯 농사 짓는 모습이 너무 깜찍하지않나요?",
  "imageUrl": "https://cdn.011st.com/11dims/resize/600x600/quality/75/11src/product/5575072075/B.jpg?51000000"
}

###
# 게시글 수정
PATCH http://localhost:3000/articles/802a7c2b-d3c5-48d7-8caf-13c6cc803d78
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxNzMwNDc2OCwiZXhwIjoxNzE3MzA1NjY4fQ.0Neh8i3gQWCU0o0y01-Co8jsW8kiXKl3dW7H6wK94pY
Content-Type: application/json

{
  "title":"판다 대박이네요",
  "content":"대나무를 잘 먹네요 ㄷㄷ",
  "imageUrl":"https://cdn.011st.com/11dims/resize/600x600/quality/75/11src/product/5575072075/B.jpg?51000000"
}

###
# 게시글 삭제
DELETE http://localhost:3000/articles/dc196ae3-0d72-4f4d-9057-a83e6bece8bc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxNzEyODU1MiwiZXhwIjoxNzE3MTI5NDUyfQ.OAcMKEyrlzrtCOlz4HXu3mmDdEQ0s-oYBlbvlHWAJUY

###
# 게시글 좋아요
PATCH http://localhost:3000/articles/2c027764-d7ef-4a94-8399-f15ffbf8f4da/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxNzEyODU1MiwiZXhwIjoxNzE3MTI5NDUyfQ.OAcMKEyrlzrtCOlz4HXu3mmDdEQ0s-oYBlbvlHWAJUY

###
# 게시글 좋아요 취소
PATCH http://localhost:3000/articles/2c027764-d7ef-4a94-8399-f15ffbf8f4da/unlike
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxNzEyODU1MiwiZXhwIjoxNzE3MTI5NDUyfQ.OAcMKEyrlzrtCOlz4HXu3mmDdEQ0s-oYBlbvlHWAJUY




### 
# 자유게시판 댓글 조회
GET http://localhost:3000/articles/287cb4c8-48c5-49e1-82fa-a1b9e2d7b4e3/comments

### 
# 자유게시판 댓글 커서 조회
GET http://localhost:3000/articles/287cb4c8-48c5-49e1-82fa-a1b9e2d7b4e3/comments?cursor=2b3c4d5e-6f7g-8h9i-0j1k-2l3m4n5o6p7q

###
# 자유게시판 댓글 등록
POST http://localhost:3000/articles/287cb4c8-48c5-49e1-82fa-a1b9e2d7b4e3/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxNzEyODU1MiwiZXhwIjoxNzE3MTI5NDUyfQ.OAcMKEyrlzrtCOlz4HXu3mmDdEQ0s-oYBlbvlHWAJUY

{
  "content":"판다가 너무 귀여워요2"
}

###
# 자유게시판 댓글 수정
PATCH http://localhost:3000/articles/287cb4c8-48c5-49e1-82fa-a1b9e2d7b4e3/comments/1d896d0e-55e9-4075-ac77-4adde865f743
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxNzEyODU1MiwiZXhwIjoxNzE3MTI5NDUyfQ.OAcMKEyrlzrtCOlz4HXu3mmDdEQ0s-oYBlbvlHWAJUY

{
  "content":"판다가 너무 귀여워요 수정"
}

###
# 자유게시판 댓글 삭제
DELETE http://localhost:3000/articles/287cb4c8-48c5-49e1-82fa-a1b9e2d7b4e3/comments/1d896d0e-55e9-4075-ac77-4adde865f743
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxNzEyODU1MiwiZXhwIjoxNzE3MTI5NDUyfQ.OAcMKEyrlzrtCOlz4HXu3mmDdEQ0s-oYBlbvlHWAJUY