POST http://localhost:3000/auth/signUp
Content-Type: application/json

{
  "email":"test52@gmail.com", 
  "password":"pandapower", 
  "name":"김판다",
  "nickname":"판다의 왕"
}

###
# 로그인

POST http://localhost:3000/auth/signIn
Content-Type: application/json

{
  "email":"test2@gmail.com", 
  "password":"pandapower"
}

###
# 토큰 재발급
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
  "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxNzQ1NjM1MywiZXhwIjoxNzE4MDYxMTUzfQ.DiX7xqEs5maByaq_RhGt382Xde4ILk9rXk95mtOraIE"
}