POST http://localhost:3000/auth/signUp
Content-Type: application/json

{
  "email":"test5@gmail.com", 
  "password":"pandapower", 
  "name":"김판다",
  "nickname":"판다의 왕"
}

###
# 로그인

POST http://localhost:3000/auth/signIn
Content-Type: application/json

{
  "email":"test5@gmail.com", 
  "password":"pandapower"
}

###
# 토큰 재발급
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
  "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsImlhdCI6MTcxNjc5MTY3NiwiZXhwIjoxNzE3Mzk2NDc2fQ.wcGjW1SsWm7OKELCcKI-1aA9rmxt1FxmE9SYAJJjgwc"
}