POST http://localhost:3000/auth/signUp
Content-Type: application/json

{
  "email":"test5@gmail.com", 
  "password":"pandapower", 
  "name":"김판다",
  "nickname":"판다의 왕"
}

###
# 로그인

POST http://localhost:3000/auth/signIn
Content-Type: application/json

{
  "email":"test5@gmail.com", 
  "password":"pandapower"
}

###
# 토큰 재발급
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
  "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImlhdCI6MTcxNjc5Mzk0NywiZXhwIjoxNzE3Mzk4NzQ3fQ.bBxra1mgW2Pe4s9KcD_8Z5QmuFAIqZhjwKEupNpkXbs"
}